- name: Destroy Owncloud infra
  hosts: localhost
  tasks:
  - name: delete Web server
    ignore_errors: true
    os_server:
       cloud: HH2_NTTE
       state: absent
       name: owncloud-web
       image: CentOS-7-x86_64-GenericCloud
       key_name: key_pedro
       timeout: 200
       flavor: 1CPU-4GB
       nics:
           - port-name: port-web

  - name: delete DB server
    ignore_errors: true
    os_server:
       cloud: HH2_NTTE
       state: absent
       name: owncloud-db
       image: CentOS-7-x86_64-GenericCloud
       key_name: key_pedro
       timeout: 200
       flavor: 1CPU-4GB
       nics:
           - port-name: port-db

  - name: delete 15g web volume
    os_volume:
      cloud: HH2_NTTE
      state: absent
      size: 15
      display_name: vol-owncloud-web

  - name: delete 15g DB volume
    os_volume:
      cloud: HH2_NTTE
      state: absent
      size: 15
      display_name: vol-owncloud-db
