---
- hosts: all
  tasks:
    - name: Install http and php etc
      yum: name={{ item }} state=present
      with_items:
         - httpd
         - php
         - php-mysql
         - mariadb-server
         - mariadb
         - sqlite
         - php-dom 
         - php-mbstring 
         - php-gd 
         - php-pdo 
         - wget 
         - bzip2
         - MySQL-python

    - name: disable SELinux permanetly
      lineinfile: dest=/etc/selinux/config regexp="^SELINUX=" line=SELINUX=disabled

    - name: disable SELinux
      shell: 'setenforce 0'

    - name: Change datadir for MariaDB
      lineinfile: dest=/etc/my.cnf regexp="^datadir=" line=datadir=/srv/mysql

    - name: create filesystem on /dev/vdb
      shell: 'parted -s -a optimal /dev/vdb mklabel msdos; parted -s -a optimal -- /dev/vdb unit compact mkpart primary ext3 1 -1; mkfs.ext3 /dev/vdb1' 
      args:
          creates: /root/create.vdb

    - name: mount /dev/vdb on /srv
      shell: 'echo "/dev/vdb1 /srv ext3 rw,seclabel,relatime,data=ordered 0 0" >> /etc/fstab; mount -a'
      args:
          creates: /root/mount.vdb

    - name: create directories on /srv for web and mysql
      shell: 'mkdir -p /srv/mysql; /bin/mysql_install_db; chown -R mysql. /srv/mysql; mkdir -p /srv/web/; chown -R apache.apache /srv/web/'
      args:
          creates: /srv/mysql

    - name: start MariaDB
      service: name=mariadb state=started

    - name: create owncloud database and user
      mysql_db: name=owncloud state=present

    - name: add mysql user for owncloud
      mysql_user: name=clouddbuser password=12345 priv=owncloud.*:ALL,GRANT state=present

    - name: download and install owncloud tarball
      shell: 'cd /srv/web/; wget -q https://download.owncloud.org/community/owncloud-8.1.1.tar.bz2; tar -jxvf owncloud-8.1.1.tar.bz2 -C /srv/web; chown -R apache.apache /srv/web/owncloud/; rm -f owncloud-8.1.1.tar.bz2; ln -s /srv/web/owncloud /var/www/html/owncloud'
      args:
           creates: /srv/web/owncloud/

    - name: start httpd
      service: name=httpd state=started
