---
# These tasks are responsible for copying the latest dev/production code from
# the version control system.

- name: download and install owncloud tarball
  shell: 'cd /srv/web/; wget -q https://download.owncloud.org/community/{{ owncloud_archive }}; tar -jxvf {{ owncloud_archive }} -C /srv/web; chown -R apache.apache /srv/web/owncloud/; rm -f {{ owncloud_archive }}; ln -s /srv/web/owncloud /var/www/html/owncloud'
  args:
       creates: /srv/web/owncloud/

- name: install the Owncloud configuration
  template: src=config.php.j2 dest=/srv/web/owncloud/config/config.php owner=apache group=apache

- name: Create Owncloud data directory
  file: path=/srv/web/owncloud/data state=directory mode=0755 owner=apache group=apache
  
- name: Activate the Onwcloud data directory
  file: path=/srv/web/owncloud/data/.ocdata state=touch owner=apache group=apache mode=0775
